# --- DURATION ---
max_steps: 10000

# --- OPTIMIZATION & STABILITY ---
grad_agg_freq: 1
grad_clip_max_norm: 1.0
monitor_grad_clip: false
amp: false

# --- LOGGING FREQUENCIES ---
rec_results_freq: 1000
rec_validation_freq: 1000
rec_inference_freq: 1000
rec_monitor_freq: 1000
rec_constraint_freq: 1000
rec_stream_freq: 1000
save_network_freq: 1000
print_stats_freq: 100
summary_freq: 1000

# --- INITIALIZATION ---
pretrain_steps: 0

# --- MISSING KEYS THAT CAUSED CRASHES ---
# 1. NTK (Neural Tangent Kernel) - Fixed your latest error
ntk:
  use_ntk: false
  save_name: null
  run_freq: 1000

# 2. Loss Function (Added safely to prevent the NEXT crash)
loss:
  _target_: physicsnemo.sym.loss.aggregator.Sum
  weights: null
